services:
  backend:
    build: ./backend
    volumes:
      - log_storage:/api/logs
    ports:
      - 8080:8000
    networks:
      - mltd
  fronted:
    build: ./fronted
    ports:
      - 3000:3000
    networks:
      - mltd

volumes:
  log_storage:

networks:
  mltd: