services:
  backend:
    build: ./backend
    volumes:
      - log_storage:/api/logs
    ports:
      - 8000:8080
    networks:
      - mltd
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - mltd

volumes:
  log_storage:

networks:
  mltd: